### ISSUE TITLE
Intall Issue

### ISSUE THREAD

**Issue by ahadel** [BadrIT/redmine_scrummer#2]
السلام عليكم
Eng Mahmoud
I have successfully run the install Command BUT the lat one 

"rake redmine_scrummer:load_default_data "
- and after selecting Language  [en]

i see this error
"Error: undefined method `update_story_size' for #Issue:0x00000005578780"
Default configuration data was not loaded.

i have restarte redmine i saw the plugin installed BUT redmine act strange and i cant open some pages cus of crash .
Please Help me in this . I use this Plugin as Scrum Course With Eng,AMR NOAMAN ,

Thanks 
SALAM.

**Comment by mahkhaled** [comment]
Thanks Ahmad for your help.
I have fixed it.

You can now update the plugin
cd plugins/redmine_scrummer
git pull origin master

and then retry
cd ../..
run the loader rake task now
