### ISSUE TITLE
Error while Adding New Sprint 

### ISSUE THREAD

**Issue by abuelnasr** [BadrIT/redmine_scrummer#4]
i got internal error while adding new Sprint 
Redmine installed without default data.
OS : Win 7 

find attached screens, 
![s1](https://f.cloud.github.com/assets/3541334/148676/8a0f6ba8-750d-11e2-8798-2fdeb990c771.png)
![s2](https://f.cloud.github.com/assets/3541334/148677/8ab4bdd8-750d-11e2-81a9-9d0ef9423cc3.png)

is there any help.
Thanks

**Comment by mahkhaled** [comment]
Make sure you run the load default data rake task before you start using the plugin.
If still receiving the error page, try to check rails logs and send me the error details.

**Comment by abuelnasr** [comment]
Thanks for your fast responding, 
Actually the bug found if you going to create new sprint from 
                   {$project}/scrummer/Sprint Planning/new version
but if make it from 
                   {$project}/settings/versions/new version 
it working good. 

## Also find below application log, 

Started GET "/scrum_userstories?project_id=test" for 127.0.0.1 at 2013-02-13 10:58:12 +0200
Processing by ScrumUserstoriesController#index as HTML
  Parameters: {"project_id"=>"test"}
  Current user: admin (id=1)
  Current user: admin (id=1)
  Rendered plugins/redmine_scrummer/app/views/scrum/_scrummer_menu.html.erb (7.0ms)
  Rendered plugins/redmine_scrummer/app/views/scrum_userstories/_inline_add.erb (19.0ms)
  Rendered queries/_filters.html.erb (7.0ms)
  Rendered queries/_columns.html.erb (1.0ms)
  Rendered issues/_sidebar.html.erb (2.0ms)
  Rendered plugins/redmine_scrummer/app/views/scrum_userstories/_statistics.html.erb (0.0ms)
  Rendered plugins/redmine_scrummer/app/views/scrum_userstories/index.html.erb within layouts/base (49.0ms)
Completed 200 OK in 170ms (Views: 60.0ms | ActiveRecord: 11.0ms)
Started GET "/scrum_sprints_planning?project_id=test" for 127.0.0.1 at 2013-02-13 10:58:17 +0200
Processing by ScrumSprintsPlanningController#index as HTML
  Parameters: {"project_id"=>"test"}
  Current user: admin (id=1)
  Rendered plugins/redmine_scrummer/app/views/scrum/_scrummer_menu.html.erb (7.0ms)
  Rendered plugins/redmine_scrummer/app/views/scrum_sprints_planning/_form.html.erb (12.0ms)
  Rendered plugins/redmine_scrummer/app/views/scrum_sprints_planning/_inline_add_version.erb (13.0ms)
  Rendered plugins/redmine_scrummer/app/views/scrum_sprints_planning/_version_row.erb (6.0ms)
  Rendered plugins/redmine_scrummer/app/views/scrum_sprints_planning/index.html.erb within layouts/base (34.0ms)
Completed 200 OK in 73ms (Views: 47.0ms | ActiveRecord: 5.0ms)
Started GET "/plugin_assets/redmine_scrummer/stylesheets/images/ui-icons_222222_256x240.png" for 127.0.0.1 at 2013-02-13 10:58:37 +0200

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_scrummer/stylesheets/images/ui-icons_222222_256x240.png"):
  actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.11) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.11) lib/rails/engine.rb:479:in`call'
  railties (3.2.11) lib/rails/application.rb:223:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in`call'
  railties (3.2.11) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in`service'
  F:/dev/Ruby/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  F:/dev/Ruby/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
  F:/dev/Ruby/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

Started POST "/scrum_sprints_planning/add_version?project_id=test" for 127.0.0.1 at 2013-02-13 10:58:48 +0200
Processing by ScrumSprintsPlanningController#add_version as HTML
  Parameters: {"utf8"=>"", "authenticity_token"=>"1VqLaViYQ+li1Cr3iS0aOwZ0KmAoy/TJI8htHQlQ7us=", "version"=>{"name"=>"0.0.2", "description"=>"", "release_id"=>"", "status"=>"open", "sharing"=>"none", "custom_field_values"=>{"1"=>"2013-02-17"}, "effective_date"=>"2013-02-21"}, "version_id"=>"", "commit"=>"Create", "project_id"=>"test"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 14ms

NoMethodError (undefined method `to_i' for #<User:0x69b5728>):
  activemodel (3.2.11) lib/active_model/attribute_methods.rb:407:in`method_missing'
  activerecord (3.2.11) lib/active_record/attribute_methods.rb:149:in `method_missing'
  activerecord (3.2.11) lib/active_record/connection_adapters/column.rb:178:in`value_to_integer'
  activerecord (3.2.11) lib/active_record/connection_adapters/column.rb:78:in `type_cast'
  activerecord (3.2.11) lib/active_record/attribute_methods/dirty.rb:86:in`_field_changed?'
  activerecord (3.2.11) lib/active_record/attribute_methods/dirty.rb:63:in `write_attribute'
  activerecord (3.2.11) lib/active_record/attribute_methods/write.rb:14:in`author_id='
  activerecord (3.2.11) lib/active_record/attribute_assignment.rb:85:in `block in assign_attributes'
  activerecord (3.2.11) lib/active_record/attribute_assignment.rb:78:in`each'
  activerecord (3.2.11) lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
  activerecord (3.2.11) lib/active_record/base.rb:497:in`initialize'
  activerecord (3.2.11) lib/active_record/reflection.rb:183:in `new'
  activerecord (3.2.11) lib/active_record/reflection.rb:183:in`build_association'
  activerecord (3.2.11) lib/active_record/associations/association.rb:233:in `build_record'
  activerecord (3.2.11) lib/active_record/associations/singular_association.rb:29:in`build'
  activerecord (3.2.11) lib/active_record/associations/builder/singular_association.rb:20:in `block in define_constructors'
  plugins/redmine_scrummer/lib/redmine_scrummer/version_patch.rb:92:in`build_wiki_page'
  plugins/redmine_scrummer/app/controllers/scrum_sprints_planning_controller.rb:120:in `create_sprint'
  plugins/redmine_scrummer/app/controllers/scrum_sprints_planning_controller.rb:68:in`add_version'
  actionpack (3.2.11) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.11) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.2.11) lib/active_support/callbacks.rb:491:in `_run__408715728__process_action__375404512__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.11) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:121:in`process'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.11) lib/action_controller/metal.rb:203:in`dispatch'
  actionpack (3.2.11) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.11) lib/action_controller/metal.rb:246:in`block in action'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:601:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in`call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.11) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `_run__501138304__call__224350511__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.11) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in`pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.11) lib/rails/engine.rb:479:in`call'
  railties (3.2.11) lib/rails/application.rb:223:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in`call'
  railties (3.2.11) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in`service'
  F:/dev/Ruby/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  F:/dev/Ruby/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'

##   F:/dev/Ruby/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

Thanks

**Comment by mahkhaled** [comment]
It is fixed now, you can update your scrummer code https://github.com/BadrIT/redmine_scrummer#update-scrummer-plugin

Thanks for letting me know, please contact me if you faced any other troubles.

**Comment by abuelnasr** [comment]
Thanks Man 
Its working well, 

is there any tutorial, fast guide.?? or could we meet on Skype and discuss optimal workflow?

Thanks
